name: "AzOps - ArmToCsv"

#
# Triggers
# trigger on commits to policies
#

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - policies

#
# Schedule
# This is an optional trigger to pull the latest Azure
# hierarchy into the Git repository in a recurring
# manner.
#
# Default: Every 6 hours
#

schedules:
  - cron: "0 */6 * * *"
    branches:
      include:
        - main
    always: true

#
# Pipelines
# Triggers this pipeline upon the completion of
# the Push pipeline.
#

#resources:
#  pipelines:
#    - pipeline: 'Pull'
#      source: 'AzOps - Push'
#      trigger:
#        branches:
#          include:
#            - main



variables:
  
  #
  # Shared variables
  # Include shared variables from the 'vars.yml' file
  # to not have to repeat them in every pipeline.
  #

  - template: .templates/vars.yml

  #
  # Folder Name
  # By default we generate the hierachy within the
  # 'azops' folder within the root of the repository.
  # If this property is modified, the config value within
  # the settings.json file - Core.State will also need
  # to be changed.
  #
  # Default: root
  #

  - name: folder
    value: "root"

  - name: policyFolder
    value: "policies"
  #
  # Branch Name
  # As part of the Pull workflow we check a temporary branch
  # this branch was previously know as system, this value can
  # be changed if this name is already reserved for other systems
  # within the repository.
  #
  # Default: automated
  #

  - name: branch
    value: "automated"

  #
  # Commit Message
  # During the Pull workflow, the changes are commited to the
  # temporary branch, the message which is applied within the
  # Git history can be changed as needed.
  #
  # Default: Automated commit
  #

  - name: commit_message
    value: "AzureFW Automated commit"

  #
  # Pull Request
  # The generated Pull Request for the Pull workflow can be
  # modified to help indicate when changes we're merged in the
  # Git history.
  #
  # Default: Automated state
  #

  - name: pull_request
    value: "AzureFw Automated State"

jobs:

  - job: pull

    #
    # Pull
    #

    displayName: "Azure Firewall GitOps Pull/Push"
    pool:
      vmImage: "ubuntu-20.04"
    
    steps:

      #
      # Checkout
      # Checks-out the repository
      #

      - checkout: self
        fetchDepth: 0
        persistCredentials: true
      #
      # Configure
      # Set global options
      #

      - task: Bash@3
        displayName: "Configure"
        inputs:
          targetType: "inline"
          script: |
            git config user.name "Azure DevOps"
            git config user.email "azuredevops@saemundsson.se"

      #
      # Checkout
      # Switch branches
      #

      - task: Bash@3
        displayName: "Checkout"
        inputs:
          targetType: "inline"
          script: |
            git checkout -b $(branch)

      #
      # AzureFwGitOps
      # Read Azure Firewall policies and generate Azure Firewall GitOps data
      #

      - template: .templates/azureFwGitOps.yml
        parameters:
          mode: "WriteToCsv"
          merge: true
          armFolder: "$(folder)/frk4-avanade (4d0765d1-ab75-4420-b750-2fafe654e5a9)/firewall"
          policyFolder: "policies"

      #
      # AzureFwGitOps
      # Write back to Azure ARM templates after merge to complete pull/push
      #

      - template: .templates/azureFwGitOps.yml
        parameters:
          mode: "WriteToArm"
          armFolder: "$(folder)/frk4-avanade (4d0765d1-ab75-4420-b750-2fafe654e5a9)/firewall"
          policyFolder: "policies"

      #
      # Status
      # Check for data changes
      #

      - task: Bash@3
        displayName: "Status"
        inputs:
          targetType: "inline"
          script: |
            STATUS=$(git status --short $(policyFolder))
            echo $STATUS
            if [ -z "$STATUS" ]
            then
              echo "##vso[task.setvariable variable=state]stop"
            else
              echo "##vso[task.setvariable variable=state]continue"
            fi

      #
      # Add
      # Add file content to index
      #

      - task: Bash@3
        displayName: "Add"
        condition: contains(variables['state'], 'continue')
        inputs:
          targetType: "inline"
          script: |
            git add ./$(policyFolder)


      #
      # Commit
      # Record changes to the repository
      #

      - task: Bash@3
        displayName: "Commit"
        condition: contains(variables['state'], 'continue')
        inputs:
          targetType: "inline"
          script: |
            git commit -m "$(commit_message)"


      #
      # Push
      # Update remote refs along with associated objects
      #

      - task: Bash@3
        displayName: "Push"
        condition: contains(variables['state'], 'continue')
        inputs:
          targetType: "inline"
          script: |
            git push origin $(branch) -f

      #
      # Merge
      # Update remote refs along with associated objects
      #

      - task: Bash@3
        displayName: "Merge"
        condition: contains(variables['state'], 'continue')
        inputs:
          targetType: "inline"
          script: |
            # Open new PR
            PROut=$(
              az repos pr create \
              --title "$(pull_request)" \
              --source-branch "$(branch)" \
              --target-branch "main" \
              --squash true \
              --delete-source-branch true \
              --auto-complete true \
            );

            # Get PR ID and check status
            PRid=$(echo $PROut | jq -r '.pullRequestId');
            PRStatus=$(az repos pr show --id $PRid | jq .status);

            # If PR is not completed, then complete it bypassing policy
            if [ $PRStatus == "\"active\"" ]; then
              echo "Completing PR bypassing branch policy"
              az repos pr update --status completed --id $PRid --bypass-policy true --bypass-policy-reason "Automated pull request" > /dev/null 2>&1
            fi;
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
